version: 2.1

orbs:
  node: circleci/node@3.0.0
executors:
  default:
    docker:
      - image: node:12

commands:
  install:
    description: "Install Packages"
    steps:
      - restore_cache:
          keys:
            - v1-yarn-{{ arch }}-{{ checksum "yarn.lock" }}
            - v1-yarn-{{ arch }}-
      - run:
          name: "Install"
          command: "yarn install"
      - save_cache:
          key: v1-yarn-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - ".yarn/cache"

jobs:
  test:
    executor: default
    steps:
      - checkout
      - install
      - run: yarn run build
      - run: yarn run test
      - run: yarn run lint
  publish:
    executor: default
    steps:
      - checkout
      - install
      - run: yarn run build
      - run: yarn version $CIRCLE_TAG
      - run: yarn config set npmAuthToken '${NPM_PUBLISH_TOKEN}'
      - run:
          name: "Publish packages"
          command: yarn workspaces foreach npm publish
workflows:
  version: 2
  test:
    jobs:
      - test
  publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          context: org-global
